version: "3.8"

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app-network
              #cpus: "0.3" # 4기준 최대 0.5 CPU 사용
              #mem_limit: 1G # 8기준 최대 1GB 메모리 사용
        restart: always

    celery:
        build: .
        command: celery -A tasks worker --concurrency=2 --loglevel=info
        depends_on:
            - redis
        networks:
            - app-network
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
              #cpus: "1.6" # 최대 3.3 CPU 사용
              #mem_limit: 6G # 최대 6GB 메모리 사용
        restart: always

    web:
        build: .
        command: python app.py
        ports:
            - "5000:5000"
        depends_on:
            - redis
        networks:
            - app-network
              #cpus: "0.1" # 최대 0.2 CPU 사용
              #mem_limit: 1G # 최대 1GB 메모리 사용
        restart: always

networks:
    app-network:
        driver: bridge

